### ISSUE TITLE
Form deletion throws error

### ISSUE THREAD

**Issue by mlaigre** [Typeform/js-api-client#32]
Hello,

Deleting a form throw the following error:

```
FetchError: invalid json response body at https://api.typeform.com/forms/Uq4A3F reason: Unexpected end of JSON input
```

Am I wrong or `204 No Content` responses are not handled ?

**Comment by anabellaspinelli** [comment]
Hey @mlaigre! 

I guess this error has to do with this line 

```javascript
        .then(response => response.json())
        .catch(error => { throw new Error(error) })
```
(https://github.com/Typeform/js-api-client/blob/93c61c944dbf3626259055a0cd11430af2c22eef/src/create-client.js#L37)

I'm not officially the maintainer but maybe I can help. Would you expect a return value in the case of `no content` or that it just doesn't `catch`?

**Comment by mlaigre** [comment]
It's look to be the point of failure. As the API returns a `204`, we expect an empty return not a failure.

I will submit a PR next week.
