### ISSUE TITLE
Feat: express middleware for verifying signature

### ISSUE THREAD

**Issue by picsoung** [Typeform/js-api-client#66]
Inspired by Twilio middleware https://www.twilio.com/docs/usage/tutorials/how-to-secure-your-express-app-by-validating-incoming-twilio-requests

offer both a middleware and a `verifySignature` function

**Comment by mathio** [comment]
@picsoung would you mind testing the version from PR #101 in an actual express project?

**Comment by mathio** [comment]
After talking with the team, we decided to move this into a separate lib. This functionality is not related to API client andit also introduces `express` as a dependency that is not necessary for the client.

I am closing this issue, but I will keep the draft PR #101 around and we can extract the code into a separate lib later.
