### ISSUE TITLE
after ignored when listing responses

### ISSUE THREAD

**Issue by SamyPesse** [Typeform/js-api-client#7]
When listing responses, it always return the same results, no matter what the `after` parameter is:

```
client.responses.list({
  uid: 'LOJytd',
  page_size: 25,
  after: '8f2794e1b3842d500430a6d8b412059a'
})

or

client.responses.list({
  uid: 'LOJytd',
  page_size: 25
})
```

It even returns the same list when the parameter `after` is not a real token.

**Comment by jepser** [comment]
Thanks for reporting it @SamyPesse, https://github.com/Typeform/js-api-client/pull/8 should fix it.

Notice that, `pageSize` has to be sent camelCased (this changed with the PR too).

**Comment by RaedsLab** [comment]
Can we reopen this issue please? 

`after` / `since` seem to be ignored as of latest version

```js
  const data = await typeformAPI.responses.list({
    uid: 'something',
    pageSize: 1000,
    after: '123456-toekn',
  });
```
